// ============================================
// CENTRALIZED STYLES FOR ALL PAGES
// ============================================
// Mengekspor styles untuk: Home, ScanPhoto, ScanVideo, ScanRealTime

// ============================================
// HOME PAGE STYLES
// ============================================
export const homeStyles = {
  container: {
    minHeight: "100vh",
    display: "flex",
    background: "#f1f5f9",
    fontFamily: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Inter", sans-serif',
    position: "relative",
    width: "100vw",
    overflowX: "hidden",
    boxSizing: "border-box",
  },
  mainContent: {
    flex: 1,
    padding: window.innerWidth < 768 ? "20px" : window.innerWidth < 1024 ? "24px" : "40px",
    overflowY: "auto",
    width: "100%",
    maxWidth: "100%",
    boxSizing: "border-box",
  },
  mobileMenuBtn: {
    position: "fixed",
    top: "20px",
    left: "20px",
    zIndex: 30,
    width: "48px",
    height: "48px",
    borderRadius: "12px",
    background: "linear-gradient(135deg, #1e293b 0%, #0f172a 100%)",
    border: "none",
    boxShadow: "0 4px 16px rgba(0, 0, 0, 0.2)",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: "24px",
  },
  pageTitle: {
    fontSize: window.innerWidth < 768 ? "24px" : "32px",
    fontWeight: "800",
    color: "#1e293b",
    marginBottom: "8px",
    letterSpacing: "-0.02em",
  },
  pageSubtitle: {
    fontSize: window.innerWidth < 768 ? "14px" : "16px",
    color: "#64748b",
    fontWeight: "500",
  },
  heroCard: {
    background: "linear-gradient(135deg, #ffffff 0%, #f8fafc 100%)",
    borderRadius: window.innerWidth < 768 ? "16px" : "24px",
    padding: window.innerWidth < 768 ? "24px" : window.innerWidth < 1024 ? "32px" : "48px",
    marginBottom: window.innerWidth < 768 ? "24px" : "32px",
    boxShadow: "0 4px 24px rgba(0, 0, 0, 0.06)",
    border: "1px solid rgba(226, 232, 240, 0.8)",
    display: "flex",
    flexDirection: window.innerWidth < 1024 ? "column" : "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: window.innerWidth < 768 ? "24px" : "48px",
  },
  aiPoweredBadge: {
    display: "inline-block",
    padding: "8px 16px",
    background: "linear-gradient(135deg, rgba(0, 188, 212, 0.1) 0%, rgba(0, 188, 212, 0.05) 100%)",
    borderRadius: "100px",
    marginBottom: "16px",
    border: "1px solid rgba(0, 188, 212, 0.2)",
  },
  badgeText: {
    fontSize: window.innerWidth < 768 ? "11px" : "13px",
    fontWeight: "700",
    color: "#00838f",
    letterSpacing: "0.5px",
  },
  heroTitle: {
    fontSize: window.innerWidth < 768 ? "20px" : window.innerWidth < 1024 ? "24px" : "28px",
    fontWeight: "800",
    color: "#0f172a",
    marginBottom: "12px",
    lineHeight: "1.3",
  },
  heroDescription: {
    fontSize: window.innerWidth < 768 ? "14px" : "16px",
    color: "#64748b",
    lineHeight: "1.6",
    marginBottom: "24px",
  },
  featureBadges: {
    display: "flex",
    flexWrap: "wrap",
    gap: "12px",
  },
  featureBadge1: {
    padding: window.innerWidth < 768 ? "10px 16px" : "12px 20px",
    background: "rgba(16, 185, 129, 0.1)",
    borderRadius: "12px",
    fontSize: window.innerWidth < 768 ? "12px" : "13px",
    fontWeight: "600",
    color: "#065f46",
  },
  featureBadge2: {
    padding: window.innerWidth < 768 ? "10px 16px" : "12px 20px",
    background: "rgba(59, 130, 246, 0.1)",
    borderRadius: "12px",
    fontSize: window.innerWidth < 768 ? "12px" : "13px",
    fontWeight: "600",
    color: "#1e3a8a",
  },
  mascotWrapper: {
    width: window.innerWidth < 768 ? "100%" : window.innerWidth < 1024 ? "240px" : "280px",
    height: window.innerWidth < 768 ? "240px" : window.innerWidth < 1024 ? "240px" : "280px",
    borderRadius: window.innerWidth < 768 ? "16px" : "24px",
    overflow: "hidden",
    boxShadow: "0 20px 40px rgba(0, 188, 212, 0.2)",
    border: "4px solid #ffffff",
    position: "relative",
    flexShrink: 0,
  },
  mascotIcon: {
    fontSize: window.innerWidth < 768 ? "120px" : "140px",
    filter: "drop-shadow(0 8px 16px rgba(0, 0, 0, 0.1))",
  },
  methodSection: {
    marginBottom: "24px",
  },
  sectionTitle: {
    fontSize: window.innerWidth < 768 ? "16px" : "18px",
    fontWeight: "700",
    color: "#1e293b",
    marginBottom: "20px",
  },
  cardGrid: {
    display: "grid",
    gridTemplateColumns:
      window.innerWidth < 768
        ? "1fr"
        : window.innerWidth < 1024
          ? "repeat(2, 1fr)"
          : "repeat(auto-fit, minmax(300px, 1fr))",
    gap: window.innerWidth < 768 ? "16px" : "20px",
  },
  card: {
    padding: window.innerWidth < 768 ? "20px" : "28px",
    background: "#ffffff",
    border: "2px solid #e2e8f0",
    borderRadius: window.innerWidth < 768 ? "16px" : "20px",
    cursor: "pointer",
    transition: "all 0.3s ease",
    textAlign: "left",
  },
  cardIcon: {
    width: window.innerWidth < 768 ? "48px" : "56px",
    height: window.innerWidth < 768 ? "48px" : "56px",
    borderRadius: window.innerWidth < 768 ? "12px" : "16px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: window.innerWidth < 768 ? "24px" : "28px",
    marginBottom: "16px",
    boxShadow: "0 8px 20px rgba(0, 0, 0, 0.1)",
  },
  cardTitle: {
    fontSize: window.innerWidth < 768 ? "16px" : "18px",
    fontWeight: "700",
    color: "#0f172a",
    marginBottom: "8px",
  },
  cardDescription: {
    fontSize: window.innerWidth < 768 ? "13px" : "14px",
    color: "#64748b",
    lineHeight: "1.5",
    marginBottom: "16px",
  },
  cardLink: {
    display: "inline-flex",
    alignItems: "center",
    gap: "6px",
    fontSize: window.innerWidth < 768 ? "13px" : "14px",
    fontWeight: "600",
  },
}

// ============================================
// SCAN PHOTO PAGE STYLES
// ============================================
export const scanPhotoStyles = {
  container: {
    minHeight: "100vh",
    display: "flex",
    background: "#f1f5f9",
    fontFamily: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Inter", sans-serif',
    position: "relative",
    width: "100vw",
    overflowX: "hidden",
    boxSizing: "border-box",
  },
  mainContent: {
    flex: 1,
    padding: window.innerWidth < 768 ? "20px" : window.innerWidth < 1024 ? "24px" : "40px",
    paddingRight: window.innerWidth < 768 ? "20px" : window.innerWidth < 1024 ? "24px" : "40px",
    overflowY: "auto",
    boxSizing: "border-box",
    width: "100%",
    maxWidth: "100%",
  },
  mobileMenuBtn: {
    position: "fixed",
    top: "20px",
    left: "20px",
    zIndex: 30,
    width: "48px",
    height: "48px",
    borderRadius: "12px",
    background: "linear-gradient(135deg, #1e293b 0%, #0f172a 100%)",
    border: "none",
    boxShadow: "0 4px 16px rgba(0, 0, 0, 0.2)",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: "24px",
    color: "#fff",
  },
  pageTitle: {
    fontSize: window.innerWidth < 768 ? "24px" : "32px",
    fontWeight: "800",
    color: "#1e293b",
    marginBottom: "8px",
    letterSpacing: "-0.02em",
  },
  pageSubtitle: {
    fontSize: window.innerWidth < 768 ? "14px" : "16px",
    color: "#64748b",
    fontWeight: "500",
  },
  heroCard: {
    background: "linear-gradient(135deg, #ffffff 0%, #f8fafc 100%)",
    borderRadius: window.innerWidth < 768 ? "16px" : "24px",
    padding: window.innerWidth < 768 ? "24px" : window.innerWidth < 1024 ? "32px" : "48px",
    marginBottom: window.innerWidth < 768 ? "24px" : "32px",
    boxShadow: "0 4px 24px rgba(0, 0, 0, 0.06)",
    border: "1px solid rgba(226, 232, 240, 0.8)",
    display: "flex",
    flexDirection: window.innerWidth < 1024 ? "column" : "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: window.innerWidth < 768 ? "24px" : "48px",
  },
  aiPoweredBadge: {
    display: "inline-block",
    padding: "8px 16px",
    background: "linear-gradient(135deg, rgba(0, 188, 212, 0.1) 0%, rgba(0, 188, 212, 0.05) 100%)",
    borderRadius: "100px",
    marginBottom: "16px",
    border: "1px solid rgba(0, 188, 212, 0.2)",
  },
  badgeText: {
    fontSize: window.innerWidth < 768 ? "11px" : "13px",
    fontWeight: "700",
    color: "#00838f",
    letterSpacing: "0.5px",
  },
  heroTitle: {
    fontSize: window.innerWidth < 768 ? "20px" : window.innerWidth < 1024 ? "24px" : "28px",
    fontWeight: "800",
    color: "#0f172a",
    marginBottom: "12px",
    lineHeight: "1.3",
  },
  heroDescription: {
    fontSize: window.innerWidth < 768 ? "14px" : "16px",
    color: "#64748b",
    lineHeight: "1.6",
    marginBottom: "24px",
  },
  featureBadges: {
    display: "flex",
    flexWrap: "wrap",
    gap: "12px",
  },
  featureBadge1: {
    padding: window.innerWidth < 768 ? "10px 16px" : "12px 20px",
    background: "rgba(16, 185, 129, 0.1)",
    borderRadius: "12px",
    fontSize: window.innerWidth < 768 ? "12px" : "13px",
    fontWeight: "600",
    color: "#065f46",
  },
  featureBadge2: {
    padding: window.innerWidth < 768 ? "10px 16px" : "12px 20px",
    background: "rgba(59, 130, 246, 0.1)",
    borderRadius: "12px",
    fontSize: window.innerWidth < 768 ? "12px" : "13px",
    fontWeight: "600",
    color: "#1e3a8a",
  },
  mascotWrapper: {
    width: window.innerWidth < 768 ? "100%" : window.innerWidth < 1024 ? "200px" : "240px",
    height: window.innerWidth < 768 ? "200px" : window.innerWidth < 1024 ? "200px" : "240px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  mascotIcon: {
    fontSize: window.innerWidth < 768 ? "120px" : "140px",
    filter: "drop-shadow(0 8px 16px rgba(0, 0, 0, 0.1))",
  },
  methodSection: {
    marginBottom: "24px",
  },
  sectionTitle: {
    fontSize: window.innerWidth < 768 ? "16px" : "18px",
    fontWeight: "700",
    color: "#1e293b",
    marginBottom: "20px",
  },
  uploadCard: {
    padding: window.innerWidth < 768 ? "20px" : "28px",
    background: "#ffffff",
    border: "2px solid #e2e8f0",
    borderRadius: window.innerWidth < 768 ? "16px" : "20px",
    cursor: "pointer",
    transition: "all 0.3s ease",
    textAlign: "center",
    maxWidth: "600px",
    margin: "0 auto",
  },
  uploadIconBox: {
    display: "flex",
    justifyContent: "center",
    marginBottom: "16px",
  },
  uploadIcon: {
    width: window.innerWidth < 768 ? "48px" : "56px",
    height: window.innerWidth < 768 ? "48px" : "56px",
    borderRadius: window.innerWidth < 768 ? "12px" : "16px",
    background: "linear-gradient(135deg, #3b82f6 0%, #2563eb 100%)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: window.innerWidth < 768 ? "24px" : "28px",
    boxShadow: "0 8px 20px rgba(59, 130, 246, 0.3)",
  },
  uploadTitle: {
    fontSize: window.innerWidth < 768 ? "16px" : "18px",
    fontWeight: "700",
    color: "#0f172a",
    marginBottom: "8px",
  },
  uploadDescription: {
    fontSize: window.innerWidth < 768 ? "13px" : "14px",
    color: "#64748b",
    lineHeight: "1.5",
    marginBottom: "16px",
  },
  chooseFileBtn: {
    display: "inline-block",
    padding: "12px 32px",
    background: "linear-gradient(135deg, #3b82f6 0%, #2563eb 100%)",
    color: "#ffffff",
    borderRadius: "10px",
    fontSize: "14px",
    fontWeight: "600",
    cursor: "pointer",
    transition: "all 0.2s ease",
    boxShadow: "0 4px 12px rgba(59, 130, 246, 0.3)",
    border: "none",
  },
  previewContainer: {
    background: "#ffffff",
    borderRadius: window.innerWidth < 768 ? "16px" : "24px",
    padding: window.innerWidth < 768 ? "20px" : "32px",
    boxShadow: "0 4px 24px rgba(0, 0, 0, 0.06)",
    maxWidth: "900px",
    margin: "0 auto",
  },
  previewHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: "24px",
  },
  previewTitle: {
    margin: 0,
    fontSize: window.innerWidth < 768 ? "18px" : "20px",
    fontWeight: "700",
    color: "#1e293b",
  },
  resetButton: {
    background: "#fee2e2",
    border: "none",
    padding: "10px 20px",
    borderRadius: "10px",
    cursor: "pointer",
    color: "#dc2626",
    fontSize: "13px",
    fontWeight: "600",
    transition: "all 0.2s ease",
  },
  previewImageContainer: {
    borderRadius: "16px",
    overflow: "hidden",
    marginBottom: "20px",
    boxShadow: "0 8px 24px rgba(0, 0, 0, 0.1)",
    background: "#f8fafc",
  },
  previewImage: {
    width: "100%",
    height: "auto",
    display: "block",
  },
  fileInfoBox: {
    display: "flex",
    alignItems: "center",
    gap: "12px",
    padding: "16px",
    background: "#f8fafc",
    borderRadius: "12px",
    marginBottom: "24px",
  },
  fileIcon: {
    fontSize: "24px",
  },
  fileName: {
    fontSize: "14px",
    color: "#475569",
    fontWeight: "500",
    flex: 1,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  detectButton: {
    width: "100%",
    padding: "16px",
    background: "linear-gradient(135deg, #10b981 0%, #059669 100%)",
    color: "#ffffff",
    border: "none",
    borderRadius: "12px",
    fontSize: "16px",
    fontWeight: "700",
    cursor: "pointer",
    transition: "all 0.2s ease",
    boxShadow: "0 8px 20px rgba(16, 185, 129, 0.3)",
  },
  resultContainer: {
    background: "#ffffff",
    borderRadius: window.innerWidth < 768 ? "16px" : "24px",
    padding: window.innerWidth < 768 ? "20px" : "32px",
    boxShadow: "0 4px 24px rgba(0, 0, 0, 0.06)",
    marginBottom: "24px",
  },
  resultHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: "24px",
  },
  resultTitle: {
    margin: 0,
    fontSize: window.innerWidth < 768 ? "20px" : "24px",
    fontWeight: "800",
    color: "#1e293b",
  },
  newScanButton: {
    background: "#ef4444",
    border: "none",
    padding: "10px 20px",
    borderRadius: "10px",
    cursor: "pointer",
    color: "#ffffff",
    fontSize: "14px",
    fontWeight: "600",
    transition: "all 0.2s ease",
  },
  detectedImageCard: {
    borderRadius: "16px",
    overflow: "hidden",
    boxShadow: "0 8px 24px rgba(0, 0, 0, 0.1)",
    marginBottom: "24px",
    border: "3px solid #10b981",
  },
  imageCardHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "12px 20px",
    background: "#ffffff",
    borderBottom: "1px solid #e2e8f0",
  },
  imageLabel: {
    fontSize: "11px",
    fontWeight: "800",
    color: "#1e293b",
    letterSpacing: "1px",
  },
  analyzedBadge: {
    fontSize: "11px",
    fontWeight: "700",
    color: "#10b981",
  },
  imageCardBody: {
    padding: "20px",
    background: "#1e293b",
    display: "flex",
    justifyContent: "center",
    minHeight: "400px",
  },
  detectedImage: {
    maxWidth: "100%",
    maxHeight: "500px",
    borderRadius: "8px",
  },
  actionButtonsContainer: {
    display: "flex",
    gap: "12px",
    justifyContent: "center",
    flexWrap: "wrap",
  },
  downloadButton: {
    padding: "12px 24px",
    background: "#3b82f6",
    color: "#ffffff",
    border: "none",
    borderRadius: "10px",
    fontSize: "14px",
    fontWeight: "600",
    cursor: "pointer",
    transition: "all 0.2s ease",
  },
  exportButton: {
    padding: "12px 24px",
    background: "#10b981",
    color: "#ffffff",
    border: "none",
    borderRadius: "10px",
    fontSize: "14px",
    fontWeight: "600",
    cursor: "pointer",
    transition: "all 0.2s ease",
    textDecoration: "none",
    display: "inline-block",
  },
  statsGrid: {
    display: "grid",
    gridTemplateColumns: window.innerWidth < 768 ? "1fr" : "repeat(auto-fit, minmax(300px, 1fr))",
    gap: "24px",
  },
  statsCard: {
    background: "#ffffff",
    borderRadius: window.innerWidth < 768 ? "16px" : "20px",
    padding: "24px",
    boxShadow: "0 4px 24px rgba(0, 0, 0, 0.06)",
  },
  statsHeader: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    background: "#1e293b",
    color: "#ffffff",
    padding: "10px 16px",
    borderRadius: "10px",
    fontSize: "11px",
    fontWeight: "700",
    marginBottom: "20px",
    letterSpacing: "1px",
  },
  statsIcon: {
    fontSize: "16px",
  },
  statsBody: {
    display: "flex",
    flexDirection: "column",
    gap: "16px",
  },
  totalBox: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "16px",
    background: "#f8fafc",
    borderRadius: "12px",
  },
  totalLabel: {
    fontSize: "14px",
    color: "#64748b",
    fontWeight: "600",
  },
  totalValue: {
    fontSize: "32px",
    fontWeight: "800",
    color: "#1e293b",
  },
  diseaseList: {
    display: "flex",
    flexDirection: "column",
    gap: "10px",
  },
  diseaseItem: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "12px",
    background: "#f8fafc",
    borderRadius: "8px",
  },
  diseaseName: {
    fontSize: "14px",
    color: "#475569",
    fontWeight: "500",
  },
  diseaseCount: {
    fontSize: "16px",
    fontWeight: "700",
    color: "#1e293b",
    padding: "4px 12px",
    background: "#e2e8f0",
    borderRadius: "6px",
  },
  noDataText: {
    fontSize: "14px",
    color: "#94a3b8",
    textAlign: "center",
    padding: "20px",
  },
  logEntry: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "12px 0",
    borderBottom: "1px solid #e2e8f0",
  },
  logLabel: {
    fontSize: "14px",
    color: "#64748b",
    fontWeight: "500",
  },
  logValue: {
    fontSize: "14px",
    color: "#1e293b",
    fontWeight: "600",
  },
  statusSuccess: {
    fontSize: "13px",
    fontWeight: "600",
    color: "#10b981",
    padding: "4px 12px",
    background: "rgba(16, 185, 129, 0.1)",
    borderRadius: "6px",
  },
  timestampText: {
    fontSize: "12px",
    color: "#94a3b8",
    padding: "12px 0",
    borderTop: "1px solid #e2e8f0",
  },
}

// ============================================
// SCAN VIDEO PAGE STYLES
// ============================================
export const scanVideoStyles = {
  container: {
    minHeight: "100vh",
    display: "flex",
    background: "#f1f5f9",
    fontFamily: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Inter", sans-serif',
    position: "relative",
    width: "100vw",
    overflowX: "hidden",
    boxSizing: "border-box",
  },
  mainContent: {
    flex: 1,
    padding: window.innerWidth < 768 ? "20px" : window.innerWidth < 1024 ? "24px" : "40px",
    paddingRight: window.innerWidth < 768 ? "20px" : window.innerWidth < 1024 ? "24px" : "40px",
    overflowY: "auto",
    width: "100%",
    maxWidth: "100%",
    boxSizing: "border-box",
  },
  mobileMenuBtn: {
    position: "fixed",
    top: "20px",
    left: "20px",
    zIndex: 30,
    width: "48px",
    height: "48px",
    borderRadius: "12px",
    background: "linear-gradient(135deg, #1e293b 0%, #0f172a 100%)",
    border: "none",
    boxShadow: "0 4px 16px rgba(0, 0, 0, 0.2)",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: "24px",
    color: "#fff",
  },
  pageTitle: {
    fontSize: window.innerWidth < 768 ? "24px" : "32px",
    fontWeight: "800",
    color: "#1e293b",
    marginBottom: "8px",
    letterSpacing: "-0.02em",
  },
  pageSubtitle: {
    fontSize: window.innerWidth < 768 ? "14px" : "16px",
    color: "#64748b",
    fontWeight: "500",
  },
  heroCard: {
    background: "linear-gradient(135deg, rgba(0, 188, 212, 0.08) 0%, rgba(15, 23, 42, 0.03) 100%)",
    borderRadius: window.innerWidth < 768 ? "16px" : "24px",
    padding: window.innerWidth < 768 ? "24px" : "40px",
    marginBottom: window.innerWidth < 768 ? "24px" : "32px",
    boxShadow: "0 4px 24px rgba(0, 0, 0, 0.06)",
    display: window.innerWidth < 768 ? "block" : "flex",
    gap: "40px",
    alignItems: "center",
    border: "1px solid rgba(0, 188, 212, 0.15)",
    width: "100%",
  },
  aiPoweredBadge: {
    display: "inline-block",
    padding: "8px 16px",
    background: "linear-gradient(135deg, rgba(0, 188, 212, 0.1) 0%, rgba(0, 188, 212, 0.05) 100%)",
    borderRadius: "100px",
    marginBottom: "16px",
    border: "1px solid rgba(0, 188, 212, 0.2)",
  },
  badgeText: {
    fontSize: window.innerWidth < 768 ? "11px" : "13px",
    fontWeight: "700",
    color: "#00838f",
    letterSpacing: "0.5px",
  },
  heroTitle: {
    fontSize: window.innerWidth < 768 ? "20px" : window.innerWidth < 1024 ? "24px" : "28px",
    fontWeight: "800",
    color: "#0f172a",
    marginBottom: "12px",
    lineHeight: "1.3",
  },
  heroDescription: {
    fontSize: window.innerWidth < 768 ? "14px" : "16px",
    color: "#64748b",
    lineHeight: "1.6",
    marginBottom: "24px",
  },
  featureBadges: {
    display: "flex",
    flexWrap: "wrap",
    gap: "12px",
  },
  featureBadge1: {
    padding: window.innerWidth < 768 ? "10px 16px" : "12px 20px",
    background: "rgba(16, 185, 129, 0.1)",
    borderRadius: "12px",
    fontSize: window.innerWidth < 768 ? "12px" : "13px",
    fontWeight: "600",
    color: "#065f46",
  },
  featureBadge2: {
    padding: window.innerWidth < 768 ? "10px 16px" : "12px 20px",
    background: "rgba(168, 85, 247, 0.1)",
    borderRadius: "12px",
    fontSize: window.innerWidth < 768 ? "12px" : "13px",
    fontWeight: "600",
    color: "#6b21a8",
  },
  mascotWrapper: {
    width: window.innerWidth < 768 ? "100%" : window.innerWidth < 1024 ? "200px" : "240px",
    height: window.innerWidth < 768 ? "200px" : window.innerWidth < 1024 ? "200px" : "240px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  mascotIcon: {
    fontSize: window.innerWidth < 768 ? "120px" : "140px",
    filter: "drop-shadow(0 8px 16px rgba(0, 0, 0, 0.1))",
  },
  methodSection: {
    marginBottom: window.innerWidth < 768 ? "24px" : "32px",
    width: "100%",
  },
  sectionTitle: {
    fontSize: window.innerWidth < 768 ? "16px" : "18px",
    fontWeight: "700",
    color: "#1e293b",
    marginBottom: "20px",
  },
  uploadCard: {
    background: "rgba(255, 255, 255, 0.4)",
    backdropFilter: "blur(10px)",
    borderRadius: window.innerWidth < 768 ? "16px" : "24px",
    padding: window.innerWidth < 768 ? "32px 20px" : "48px 40px",
    boxShadow: "0 8px 32px rgba(0, 0, 0, 0.08)",
    border: "2px dashed rgba(168, 85, 247, 0.3)",
    textAlign: "center",
    transition: "all 0.3s ease",
    maxWidth: window.innerWidth < 768 ? "100%" : window.innerWidth < 1024 ? "600px" : "800px",
    margin: "0 auto",
    width: "100%",
  },
  uploadIconBox: {
    display: "flex",
    justifyContent: "center",
    marginBottom: "16px",
  },
  uploadIcon: {
    width: window.innerWidth < 768 ? "48px" : "56px",
    height: window.innerWidth < 768 ? "48px" : "56px",
    borderRadius: window.innerWidth < 768 ? "12px" : "16px",
    background: "linear-gradient(135deg, #a855f7 0%, #9333ea 100%)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: window.innerWidth < 768 ? "24px" : "28px",
    boxShadow: "0 8px 20px rgba(168, 85, 247, 0.3)",
  },
  uploadTitle: {
    fontSize: window.innerWidth < 768 ? "16px" : "18px",
    fontWeight: "700",
    color: "#0f172a",
    marginBottom: "8px",
  },
  uploadDescription: {
    fontSize: window.innerWidth < 768 ? "13px" : "14px",
    color: "#64748b",
    lineHeight: "1.5",
    marginBottom: "16px",
  },
  chooseFileBtn: {
    display: "inline-block",
    padding: "12px 32px",
    background: "linear-gradient(135deg, #a855f7 0%, #9333ea 100%)",
    color: "#ffffff",
    borderRadius: "10px",
    fontSize: "14px",
    fontWeight: "600",
    cursor: "pointer",
    transition: "all 0.2s ease",
    boxShadow: "0 4px 12px rgba(168, 85, 247, 0.3)",
    border: "none",
  },
  previewContainer: {
    background: "rgba(255, 255, 255, 0.5)",
    backdropFilter: "blur(10px)",
    borderRadius: window.innerWidth < 768 ? "16px" : "24px",
    padding: window.innerWidth < 768 ? "20px" : "32px",
    boxShadow: "0 4px 24px rgba(0, 0, 0, 0.06)",
    maxWidth: window.innerWidth < 768 ? "100%" : window.innerWidth < 1024 ? "720px" : "1200px",
    margin: "0 auto",
    width: "100%",
  },
  previewHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: "24px",
  },
  previewTitle: {
    margin: 0,
    fontSize: window.innerWidth < 768 ? "18px" : "20px",
    fontWeight: "700",
    color: "#1e293b",
  },
  resetButton: {
    background: "#fee2e2",
    border: "none",
    padding: "10px 20px",
    borderRadius: "10px",
    cursor: "pointer",
    color: "#dc2626",
    fontSize: "13px",
    fontWeight: "600",
    transition: "all 0.2s ease",
  },
  previewImageContainer: {
    borderRadius: "16px",
    overflow: "hidden",
    marginBottom: "20px",
    boxShadow: "0 8px 24px rgba(0, 0, 0, 0.1)",
    background: "#f8fafc",
  },
  fileInfoBox: {
    display: "flex",
    alignItems: "center",
    gap: "12px",
    padding: "16px",
    background: "#f8fafc",
    borderRadius: "12px",
    marginBottom: "24px",
  },
  fileIcon: {
    fontSize: "24px",
  },
  fileName: {
    fontSize: "14px",
    color: "#475569",
    fontWeight: "500",
    flex: 1,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  detectButton: {
    width: "100%",
    padding: "16px",
    background: "linear-gradient(135deg, #a855f7 0%, #9333ea 100%)",
    color: "#ffffff",
    border: "none",
    borderRadius: "12px",
    fontSize: "16px",
    fontWeight: "700",
    cursor: "pointer",
    transition: "all 0.2s ease",
    boxShadow: "0 8px 20px rgba(168, 85, 247, 0.3)",
  },
  resultContainer: {
    background: "#ffffff",
    borderRadius: window.innerWidth < 768 ? "16px" : "24px",
    padding: window.innerWidth < 768 ? "20px" : "32px",
    boxShadow: "0 4px 20px rgba(0, 0, 0, 0.06)",
    marginBottom: "24px",
    maxWidth: window.innerWidth < 768 ? "100%" : window.innerWidth < 1024 ? "720px" : "1200px",
    margin: "0 auto 24px auto",
    width: "100%",
  },
  resultHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: "24px",
  },
  resultTitle: {
    margin: 0,
    fontSize: window.innerWidth < 768 ? "20px" : "24px",
    fontWeight: "800",
    color: "#1e293b",
  },
  newScanButton: {
    background: "#ef4444",
    border: "none",
    padding: "10px 20px",
    borderRadius: "10px",
    cursor: "pointer",
    color: "#ffffff",
    fontSize: "14px",
    fontWeight: "600",
    transition: "all 0.2s ease",
  },
  detectedImageCard: {
    borderRadius: "16px",
    overflow: "hidden",
    boxShadow: "0 8px 24px rgba(0, 0, 0, 0.1)",
    marginBottom: "24px",
    border: "3px solid #a855f7",
  },
  imageCardHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "12px 20px",
    background: "#ffffff",
    borderBottom: "1px solid #e2e8f0",
  },
  imageLabel: {
    fontSize: "11px",
    fontWeight: "800",
    color: "#1e293b",
    letterSpacing: "1px",
  },
  analyzedBadge: {
    fontSize: "11px",
    fontWeight: "700",
    color: "#a855f7",
  },
  imageCardBody: {
    padding: "20px",
    background: "#1e293b",
    display: "flex",
    justifyContent: "center",
    minHeight: "400px",
  },
  actionButtonsContainer: {
    display: "flex",
    gap: "12px",
    justifyContent: "center",
    flexWrap: "wrap",
  },
  exportButton: {
    padding: "12px 24px",
    background: "#a855f7",
    color: "#ffffff",
    border: "none",
    borderRadius: "10px",
    fontSize: "14px",
    fontWeight: "600",
    cursor: "pointer",
    transition: "all 0.2s ease",
    textDecoration: "none",
    display: "inline-block",
  },
  summaryCardsWrapper: {
    display: "grid",
    gridTemplateColumns: window.innerWidth < 768 ? "1fr" : window.innerWidth < 1024 ? "1fr" : "1fr 1fr",
    gap: "24px",
    maxWidth: window.innerWidth < 768 ? "100%" : window.innerWidth < 1024 ? "720px" : "1200px",
    margin: "0 auto",
    width: "100%",
  },
  summaryCard: {
    background: "#ffffff",
    borderRadius: window.innerWidth < 768 ? "16px" : "20px",
    padding: window.innerWidth < 768 ? "20px" : "28px",
    boxShadow: "0 4px 20px rgba(0, 0, 0, 0.06)",
    border: "1px solid #e2e8f0",
    width: "100%",
  },
  statsHeader: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    background: "#1e293b",
    color: "#ffffff",
    padding: "10px 16px",
    borderRadius: "10px",
    fontSize: "11px",
    fontWeight: "700",
    marginBottom: "20px",
    letterSpacing: "1px",
  },
  statsIcon: {
    fontSize: "16px",
  },
  diseaseTable: {
    marginTop: "20px",
    border: "1px solid #e2e8f0",
    borderRadius: "12px",
    overflow: "hidden",
  },
  tableHeader: {
    display: "grid",
    gridTemplateColumns: "2fr 1fr",
    gap: "10px",
    padding: "12px 15px",
    backgroundColor: "#334155",
    color: "#fff",
    fontWeight: "600",
    fontSize: "13px",
  },
  tableHeaderCell: {
    textAlign: "left",
  },
  tableRow: {
    display: "grid",
    gridTemplateColumns: "2fr 1fr",
    gap: "10px",
    padding: "12px 15px",
    borderBottom: "1px solid #e2e8f0",
    backgroundColor: "#fff",
  },
  tableCellDisease: {
    fontSize: "14px",
    color: "#1e293b",
    fontWeight: "500",
  },
  tableCellCount: {
    fontSize: "14px",
    color: "#475569",
    fontWeight: "600",
  },
  logCard: {
    padding: "5px",
  },
  logHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: "15px",
    paddingBottom: "15px",
    borderBottom: "2px solid #e2e8f0",
  },
  logTitle: {
    margin: 0,
    fontSize: "16px",
    color: "#1e293b",
    fontWeight: "600",
  },
  statusBadge: {
    padding: "6px 14px",
    borderRadius: "20px",
    fontSize: "12px",
    fontWeight: "700",
    letterSpacing: "0.5px",
  },
  logDetails: {
    marginBottom: "20px",
  },
  logText: {
    margin: "8px 0",
    fontSize: "14px",
    color: "#64748b",
    fontWeight: "500",
  },
  timestampBox: {
    marginTop: "12px",
    padding: "12px",
    backgroundColor: "#f1f5f9",
    borderRadius: "8px",
    borderLeft: "4px solid #a855f7",
  },
  timestampLabel: {
    fontSize: "12px",
    color: "#64748b",
    fontWeight: "600",
    display: "block",
    marginBottom: "4px",
  },
  timestampValue: {
    fontSize: "13px",
    color: "#1e293b",
    fontWeight: "500",
  },
}

// ============================================
// SCAN REALTIME PAGE STYLES
// ============================================
export const scanRealtimeStyles = {
  container: {
    minHeight: "100vh",
    display: "flex",
    background: "#f1f5f9",
    fontFamily: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Inter", sans-serif',
    position: "relative",
    width: "100vw",
    overflowX: "hidden",
    boxSizing: "border-box",
  },
  mainContent: {
    flex: 1,
    padding: window.innerWidth < 768 ? "20px" : window.innerWidth < 1024 ? "24px" : "40px",
    paddingRight: window.innerWidth < 768 ? "20px" : window.innerWidth < 1024 ? "24px" : "40px",
    overflowY: "auto",
    width: "100%",
    maxWidth: "100%",
    boxSizing: "border-box",
  },
  mobileMenuBtn: {
    position: "fixed",
    top: "20px",
    left: "20px",
    zIndex: 30,
    width: "48px",
    height: "48px",
    borderRadius: "12px",
    background: "linear-gradient(135deg, #1e293b 0%, #0f172a 100%)",
    border: "none",
    boxShadow: "0 4px 16px rgba(0, 0, 0, 0.2)",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: "24px",
    color: "#fff",
  },
  pageTitle: {
    fontSize: window.innerWidth < 768 ? "24px" : "32px",
    fontWeight: "800",
    color: "#1e293b",
    marginBottom: "8px",
    letterSpacing: "-0.02em",
  },
  pageSubtitle: {
    fontSize: window.innerWidth < 768 ? "14px" : "16px",
    color: "#64748b",
    fontWeight: "500",
  },
  heroCard: {
    background: "linear-gradient(135deg, rgba(0, 188, 212, 0.08) 0%, rgba(15, 23, 42, 0.03) 100%)",
    borderRadius: window.innerWidth < 768 ? "16px" : "24px",
    padding: window.innerWidth < 768 ? "24px" : "40px",
    marginBottom: window.innerWidth < 768 ? "24px" : "32px",
    boxShadow: "0 4px 24px rgba(0, 0, 0, 0.06)",
    display: window.innerWidth < 768 ? "block" : "flex",
    gap: "40px",
    alignItems: "center",
    border: "1px solid rgba(0, 188, 212, 0.15)",
    width: "100%",
  },
  aiPoweredBadge: {
    display: "inline-block",
    padding: "8px 16px",
    background: "linear-gradient(135deg, rgba(0, 188, 212, 0.1) 0%, rgba(0, 188, 212, 0.05) 100%)",
    borderRadius: "100px",
    marginBottom: "16px",
    border: "1px solid rgba(0, 188, 212, 0.2)",
  },
  badgeText: {
    fontSize: window.innerWidth < 768 ? "11px" : "13px",
    fontWeight: "700",
    color: "#00838f",
    letterSpacing: "0.5px",
  },
  heroTitle: {
    fontSize: window.innerWidth < 768 ? "20px" : window.innerWidth < 1024 ? "24px" : "28px",
    fontWeight: "800",
    color: "#0f172a",
    marginBottom: "12px",
    lineHeight: "1.3",
  },
  heroDescription: {
    fontSize: window.innerWidth < 768 ? "14px" : "16px",
    color: "#64748b",
    lineHeight: "1.6",
    marginBottom: "24px",
  },
  featureBadges: {
    display: "flex",
    flexWrap: "wrap",
    gap: "12px",
  },
  featureBadge1: {
    padding: window.innerWidth < 768 ? "10px 16px" : "12px 20px",
    background: "rgba(16, 185, 129, 0.1)",
    borderRadius: "12px",
    fontSize: window.innerWidth < 768 ? "12px" : "13px",
    fontWeight: "600",
    color: "#065f46",
  },
  featureBadge2: {
    padding: window.innerWidth < 768 ? "10px 16px" : "12px 20px",
    background: "rgba(59, 130, 246, 0.1)",
    borderRadius: "12px",
    fontSize: window.innerWidth < 768 ? "12px" : "13px",
    fontWeight: "600",
    color: "#1e3a8a",
  },
  mascotWrapper: {
    width: window.innerWidth < 768 ? "100%" : window.innerWidth < 1024 ? "200px" : "240px",
    height: window.innerWidth < 768 ? "200px" : window.innerWidth < 1024 ? "200px" : "240px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  mascotIcon: {
    fontSize: window.innerWidth < 768 ? "120px" : "140px",
    filter: "drop-shadow(0 8px 16px rgba(0, 0, 0, 0.1))",
  },
  methodSection: {
    marginBottom: window.innerWidth < 768 ? "24px" : "32px",
    width: "100%",
  },
  sectionTitle: {
    fontSize: window.innerWidth < 768 ? "16px" : "18px",
    fontWeight: "700",
    color: "#1e293b",
    marginBottom: "16px",
  },
  videoCard: {
    background: "rgba(255, 255, 255, 0.5)",
    backdropFilter: "blur(10px)",
    borderRadius: "16px",
    padding: "24px",
    boxShadow: "0 4px 24px rgba(0, 0, 0, 0.06)",
    border: "1px solid rgba(255, 255, 255, 0.8)",
    marginBottom: window.innerWidth < 1024 ? "24px" : "0",
  },
  summaryCard: {
    background: "rgba(255, 255, 255, 0.5)",
    backdropFilter: "blur(10px)",
    borderRadius: "16px",
    padding: "24px",
    boxShadow: "0 4px 24px rgba(0, 0, 0, 0.06)",
    border: "1px solid rgba(255, 255, 255, 0.8)",
  },
  cardHeader: {
    display: "flex",
    alignItems: "center",
    gap: "12px",
    fontSize: "16px",
    fontWeight: "700",
    color: "#1e293b",
    marginBottom: "16px",
    paddingBottom: "12px",
    borderBottom: "2px solid rgba(0, 188, 212, 0.2)",
  },
  actionButton: {
    width: "100%",
    padding: "14px 24px",
    borderRadius: "12px",
    border: "none",
    color: "#ffffff",
    fontSize: "15px",
    fontWeight: "600",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "10px",
    transition: "all 0.2s ease",
    marginTop: "16px",
    boxShadow: "0 4px 12px rgba(0, 0, 0, 0.1)",
  },
  summaryContent: {
    minHeight: "300px",
    display: "flex",
    flexDirection: "column",
  },
  summaryTable: {
    width: "100%",
    borderCollapse: "separate",
    borderSpacing: "0 8px",
  },
  tableHeader: {
    textAlign: "left",
    padding: "12px",
    fontSize: "13px",
    fontWeight: "700",
    color: "#64748b",
    textTransform: "uppercase",
    letterSpacing: "0.5px",
  },
  tableRow: {
    background: "rgba(255, 255, 255, 0.6)",
    transition: "all 0.2s ease",
  },
  tableCell: {
    padding: "16px 12px",
    fontSize: "14px",
    color: "#475569",
  },
  badge: {
    padding: "6px 12px",
    borderRadius: "8px",
    fontSize: "12px",
    fontWeight: "700",
    display: "inline-block",
  },
  emptyState: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    height: "100%",
    minHeight: "300px",
  },
  infoCard: {
    background: "linear-gradient(135deg, rgba(59, 130, 246, 0.08) 0%, rgba(59, 130, 246, 0.03) 100%)",
    borderRadius: "16px",
    padding: "24px",
    display: "flex",
    gap: "16px",
    border: "1px solid rgba(59, 130, 246, 0.15)",
  },
  infoIcon: {
    fontSize: "24px",
    flexShrink: 0,
  },
  infoText: {
    fontSize: "14px",
    color: "#64748b",
    lineHeight: "1.6",
  },
}
